### ISSUE TITLE
Change the error highlighter style

### ISSUE THREAD

**Issue by Gozala** [lukehoban/atom-ide-flow#42]
Often times if flow errors many of them overlaps, in which case layers of red highlight makes it impossible to see or navigate around the code. Would be nice to change a style so it's possible to still navigate and edit code normally

<img width="454" alt="screen shot 2015-10-13 at 6 33 06 pm" src="https://cloud.githubusercontent.com/assets/21236/10472739/e7333a6a-71d8-11e5-8fdf-d9e84521bc4a.png">

**Comment by tlrobinson** [comment]
+1, this is quite annoying.

**Comment by yann-stepienik-cko** [comment]
I quite like how the red highlight is different from other kind of highlight, but it definitely need to be readable without killing your eyes...

![screen shot 2016-08-26 at 11 28 24](https://cloud.githubusercontent.com/assets/17568523/18002521/3928075a-6b80-11e6-8b66-f426926d1d94.png)

**Comment by justin-calleja** [comment]
A quick fix for now:

Open atom stylesheet via Atom menu -> Stylesheet

(or open <home>/.atom/styles.less)

Then add:

``` css
atom-text-editor::shadow {
  .ide-flow-error {
    background-color: unset;
  }
  .highlight {
    &.ide-flow-error .region {
      background: #F6F7EB;
      z-index: -1;
    }
  }
}
```
